# Test application
import sys
from cerberus_kind import Validator
from pprint import pprint

schema = {'__root__': {'type': 'dict',
                       'selector': {'project': {'apiVersion': {'type': 'string',
                                                               'regex': 'v[0-9]+',
                                                               'default': 'v1',
                                                               'order': 0},
                                                'name': {'type': 'string',
                                                         'required': True,
                                                         'empty': False,
                                                         'order': 1},
                                                'version': {'type': 'string',
                                                            'regex': '[0-9]+\\.[0-9]+\\.[0-9]+',
                                                            'default': '0.0.1',
                                                            'order': 2},
                                                'maintainer': {'type': 'string',
                                                               'default': 'codespace',
                                                               'order': 3},
                                                'workdir': {'type': 'string',
                                                            'default': '.',
                                                            'order': 4},
                                                'workspace': {'type': 'dict',
                                                              'selector': {'workspace': {'base': {'type': 'string',
                                                                                         'regex': '(?:.+/)?([^:]+)(?::.+)?',
                                                                                                  'required': True},
                                                                                         'preps': {'type': 'list',
                                                                                                   'schema': {'type': 'dict',
                                                                                                              'schema': {'run': {'type': 'string'},
                                                                                                                         'add': {'type': 'string'},
                                                                                                                         'pip': {'type': 'string'},
                                                                                                                         'apt': {'type': 'string'},
                                                                                                                         'yum': {'type': 'string'},
                                                                                                                         'apk': {'type': 'string'}}}},
                                                                                         'ignores': {'type': 'list',
                                                                                                     'default': ['**/.*'],
                                                                                                     'schema': {'type': 'string'}},
                                                                                         'script': {'type': 'string'},
                                                                                         'env': {'type': 'dict',
                                                                                                 'valuesrules': {'schema': {'type': ['string']}},
                                                                                                 'default': {'PYTHONUNBUFFERED': '1'}},
                                                                                         'command': {'type': ['string',
                                                                                                     'list']},
                                                                                         'args': {'type': ['string',
                                                                                                  'list']}},
                                                                           'buildscript': {'buildscript': {'type': 'string',
                                                                                                           'default': 'FROM    '
                                                                                                           'python:latest',
                                                                                                           'required': True},
                                                                                           'ignores': {'type': 'list',
                                                                                                       'default': ['**/.*'],
                                                                                                       'schema': {'type': 'string'}}},
                                                                           'dockerfile': {'filePath': {'type': 'string',
                                                                                                       'default': 'Dockerfile',
                                                                                                       'required': True},
                                                                                          'ignorePath': {'type': 'string',
                                                                                                         'default': '.dockerignore'}}},
                                                              'order': 10},
                                                'ingress': {'type': 'dict',
                                                            'valuesrules': {'type': 'dict',
                                                                            'schema': {'target': {'type': 'string',
                                                                                                  'regex': '[A-Za-z0-9-_]+:[0-9]+',
                                                                                                  'required': True},
                                                                                       'rewritePath': {'type': 'boolean',
                                                                                                       'default': True}}},
                                                            'order': 20},
                                                'app': {'type': 'dict',
                                                        'valuesrules': {'type': 'dict',
                                                                        'selector': {'app': {'image': {'type': 'string',
                                                                                                       'regex': '(?:.+/)?([^:]+)(?::.+)?'},
                                                                                             'env': {'type': 'dict'},
                                                                                             'ports': {'type': 'list',
                                                                                                       'schema': {'type': 'integer'}},
                                                                                             'command': {'type': ['string',
                                                                                                         'list']},
                                                                                             'args': {'type': ['string',
                                                                                                      'list']},
                                                                                             'mounts': {'type': 'list',
                                                                                                        'schema': {'type': 'string',
                                                                                                                   'regex': '[A-Za-z0-9-_]+:/\\w+'}},
                                                                                             'constraints': {'type': 'dict',
                                                                                                             'schema': {'hostname': {'type': 'string'},
                                                                                                                        'label': {'type': 'dict'}}},
                                                                                             'restartPolicy': {'type': 'string',
                                                                                                               'allowed': ['never',
                                                                                                                           'onFailure',
                                                                                                                           'always'],
                                                                                                               'default': 'never',
                                                                                                               'excludes': 'runSpec'},
                                                                                             'scale': {'type': 'integer',
                                                                                                       'default': 1,
                                                                                                       'excludes': 'runSpec'},
                                                                                             'quota': {'type': 'dict',
                                                                                                       'excludes': 'resources',
                                                                                                       'schema': {'cpu': {'type': 'number'},
                                                                                                                  'gpu': {'type': 'integer'},
                                                                                                                  'mem': {'type': 'string',
                                                                                                                          'regex': '[0-9]+[GMK]?[i]?'}}}},
                                                                                     'job': {'image': {'type': 'string',
                                                                                                       'regex': '(?:.+/)?([^:]+)(?::.+)?'},
                                                                                             'env': {'type': 'dict'},
                                                                                             'ports': {'type': 'list',
                                                                                                       'schema': {'type': 'integer'}},
                                                                                             'command': {'type': ['string',
                                                                                                         'list']},
                                                                                             'args': {'type': ['string',
                                                                                                      'list']},
                                                                                             'mounts': {'type': 'list',
                                                                                                        'schema': {'type': 'string',
                                                                                                                   'regex': '[A-Za-z0-9-_]+:/\\w+'}},
                                                                                             'constraints': {'type': 'dict',
                                                                                                             'schema': {'hostname': {'type': 'string'},
                                                                                                                        'label': {'type': 'dict'}}},
                                                                                             'resources': {'type': 'dict',
                                                                                                           'excludes': 'quota',
                                                                                                           'schema': {'limits': {'type': 'dict',
                                                                                                                                 'schema': {'cpu': {'type': 'number'},
                                                                                                                                            'gpu': {'type': 'integer'},
                                                                                                                                            'mem': {'type': 'string',
                                                                                                                                                    'regex': '[0-9]+[GMK]?[i]?'}}},
                                                                                                                      'requests': {'type': 'dict',
                                                                                                                                   'schema': {'cpu': {'type': 'number'},
                                                                                                                                              'gpu': {'type': 'integer'},
                                                                                                                                              'mem': {'type': 'string',
                                                                                                                                                      'regex': '[0-9]+[GMK]?[i]?'}}}}},
                                                                                             'runSpec': {'type': 'dict',
                                                                                                         'excludes': 'restartPolicy',
                                                                                                         'default': {'restartPolicy': None,
                                                                                                                     'parallelism': None,
                                                                                                                     'completion': None},
                                                                                                         'schema': {'restartPolicy': {'type': 'string',
                                                                                                                                      'allowed': ['never',
                                                                                                                                                  'onFailure'],
                                                                                                                                      'default': 'never'},
                                                                                                                    'parallelism': {'type': 'integer',
                                                                                                                                    'default': 1},
                                                                                                                    'completion': {'type': 'integer',
                                                                                                                                   'default': 1}}}},
                                                                                     'service': {'image': {'type': 'string',
                                                                                                           'regex': '(?:.+/)?([^:]+)(?::.+)?'},
                                                                                                 'env': {'type': 'dict'},
                                                                                                 'ports': {'type': 'list',
                                                                                                           'schema': {'type': 'integer'}},
                                                                                                 'command': {'type': ['string',
                                                                                                             'list']},
                                                                                                 'args': {'type': ['string',
                                                                                                          'list']},
                                                                                                 'mounts': {'type': 'list',
                                                                                                            'schema': {'type': 'string',
                                                                                                                       'regex': '[A-Za-z0-9-_]+:/\\w+'}},
                                                                                                 'constraints': {'type': 'dict',
                                                                                                                 'schema': {'hostname': {'type': 'string'},
                                                                                                                            'label': {'type': 'dict'}}},
                                                                                                 'resources': {'type': 'dict',
                                                                                                               'excludes': 'quota',
                                                                                                               'schema': {'limits': {'type': 'dict',
                                                                                                                                     'schema': {'cpu': {'type': 'number'},
                                                                                                                                                'gpu': {'type': 'integer'},
                                                                                                                                                'mem': {'type': 'string',
                                                                                                                                                        'regex': '[0-9]+[GMK]?[i]?'}}},
                                                                                                                          'requests': {'type': 'dict',
                                                                                                                                       'schema': {'cpu': {'type': 'number'},
                                                                                                                                                  'gpu': {'type': 'integer'},
                                                                                                                                                  'mem': {'type': 'string',
                                                                                                                                                          'regex': '[0-9]+[GMK]?[i]?'}}}}},
                                                                                                 'runSpec': {'type': 'dict',
                                                                                                             'excludes': 'restartPolicy',
                                                                                                             'default': {'replicas': None,
                                                                                                                         'autoscaler': {'enable': None}},
                                                                                                             'schema': {'replicas': {'type': 'integer',
                                                                                                                                     'default': 1},
                                                                                                                        'autoscaler': {'type': 'dict',
                                                                                                                                       'schema': {'enable': {'type': 'boolean',
                                                                                                                                                             'default': False},
                                                                                                                                                  'min': {'type': 'integer',
                                                                                                                                                          'default': 1},
                                                                                                                                                  'max': {'type': 'integer',
                                                                                                                                                          'default': 1},
                                                                                                                                                  'metrics': {'type': 'list',
                                                                                                                                                              'schema': {'type': 'dict',
                                                                                                                                                                         'schema': {'resources': {'type': 'string',
                                                                                                                                                                                                  'allowed': ['cpu'],
                                                                                                                                                                                                  'default': 'cpu'}}}}}}}}}}},
                                                        'order': 30}}}}}

document = {'name': 'Your Project',
            'version': '0.0.1',
            'maintainer': 'codespace',
            'kind': 'Project',
            'workspace': {'kind': 'Dockerfile', 'filePath': '.'},
            'ingress': {'TEST_INGRESS': {'target': 'test:1234'}},
            'app': {'server': {'kind': 'Service',
                    'command': 'python server.py',
                               'ports': [5555]}}}

if __name__ == '__main__':
    print("* Schema *")
    pprint(schema, sort_dicts=False)
    print("* Document *")
    pprint(document, sort_dicts=False)
    v = Validator(schema)
    if v.validate(document):
        print("[Verified]")
        pprint(v.normalized_by_order(document), sort_dicts=False)
    else:
        print("[Errors]", v.errors)
        sys.exit(1)
